schema_version: 20180708
name: create
version: 0.0.1
runtime: java
cmd: io.fnproject.example.CreateEmployeeFunction::handle
build_image: oracle-atp-base-build
run_image: oracle-atp-base-run
format: http
timeout: 100
triggers:
- name: create_trigger
  type: http
  source: /create
